### ISSUE TITLE
Error Deploying sample project to AWS Mobile Hub (Section _'Backend Setup'_)

### ISSUE THREAD

**Issue by 1stDMann** [awslabs/aws-mobile-react-native-starter#17] opened 2017-10-28 22:59 UTC
Hi,

I try to follow the sample project, but when I press the _'Deploy to AWS Mobile Hub'_-Button (Section _'Backend Setup'_, Step 1) I always get following error:
![aws-mobile-hub-errormsg](https://user-images.githubusercontent.com/33163632/32139189-84d1af58-bc42-11e7-8b8d-d9f27228bcd6.JPG)

I tried out (nearly) all regions, always with the same result,

Even the manual import failed with the same error message:
![aws-mobile-hub-errormsg-import](https://user-images.githubusercontent.com/33163632/32139275-59f7e7fa-bc44-11e7-9387-9e4b53bdba93.JPG)

Any idea what the problem is?

Best regards
DMa

**Comment by mjmaix** [comment] 2017-10-29 04:09
might be a duplicate of #4

**Comment by RTHRELKELD1980** [comment] 2017-10-29 17:04
Are you on a lower latency connection? What geographic region are you in? As @mjmaix mentioned this could be a duplicate and we're working on a resolution for that issue.

**Comment by 1stDMann** [comment] 2017-10-29 19:56
I tried it from my home desktop with a cable connection (no WLAN or 3g).
Is there anybody not having the same problem?

**Comment by richardzcode** [comment] 2017-10-29 22:21
@1stDMann Let's see if it is caused by previous incomplete import.

Could you go to AWS Console, then check these services:
Cognito -> See if there is any "reactnativestarter" userpool.
S3 -> See if there is any "reactnativestarter" bucket.
Lambda -> See if there is any "Pets" functions already exist.

Also, one case my friend had was he had reached some quota on S3 or something, he got the similar error.

**Comment by 1stDMann** [comment] 2017-10-30 20:34
I checked the mentioned AWS service and there was nothing.
Because I have no other projects on AWS I dont think it's a resource problem.

**Comment by mlabieniec** [comment] 2017-12-21 04:47
This should be fixed similarly to #4 please reopen if needed.

**Closed by mlabieniec** 2017-12-21 04:47 UTC
Labels: AWS Mobile Hub
