### ISSUE TITLE
cant sign up due to phone number issues

### ISSUE THREAD

**Issue by shimoni** [awslabs/aws-mobile-react-native-starter#37] opened 2017-12-31 10:33 UTC
I am trying to use this starter app and when i run it on my emulator i cant sign up.
i put here a screenshot with my emulator and the problem. please help me :)

![capture](https://user-images.githubusercontent.com/32243904/34460952-7047ae0a-ee26-11e7-9a1a-fea37edef148.PNG)

**Comment by twoolf** [comment] 2017-12-31 13:50
In my case it worked right off (both emulator and device) -- I'd suggest making sure that you've got the number right, ignoring the warning about the timer (its not a blocker).  Similarly, the note at the top about the phone number format is a reminder, not a blocker on it working.  If you don't have SMS text enabled on your phone, try it with another number that does support that, since that might also be the problem you are having.

**Comment by aalkz** [comment] 2018-01-05 03:12
I'm having the exact same problem, tried on a physical device (Android). I even tried +12223334444 and I can't move past the Sign Up screen. It does create the user in Cognito though, it just leaves it UNCONFIRMED.

**Comment by twoolf** [comment] 2018-01-05 14:27
out of curiousity, since I can't tell from your note -- is the phone number you are using going to an actual, working phone?  This part of the App works just fine for me, but you do need to be able to use the code generated back to your phone for registration and login
 Also, if you get past this, I would be curious if you can read/write to the DynamoDB tables.  I can upload to S3 from within the App, but the DynamoDB connection is continuing to fail.  I suspect something changed within a version, but if DynamoDB connection works for you, that would help with debugging.

**Comment by aalkz** [comment] 2018-01-05 23:01
Yes, I also tried with a working phone number, and I never got the SMS needed to continue. I tried de +12223334444 example only to comply with the format, but it didn't show me the "enter the code we sent you" dialog either, it just kept showing the phone number format error.

The DynamoDB part doesn't work in my tests either.

**Comment by elorzafe** [comment] 2018-01-13 00:32
This issue was fixed with the latest version, please take a look and feel free to reopen this issue in case you have any problems.

**Closed by elorzafe** 2018-01-13 00:32 UTC
