### ISSUE TITLE
undefined is not an object (evaluating '_react2.PropTypes.string')

### ISSUE THREAD

**Issue by Dimitrios6** [awslabs/aws-mobile-react-native-starter#18] opened 2017-10-29 15:13 UTC
In my opinion after version 15.5 of React we have to import PropTypes from prop-types in the MFAPrompt.js file like "_import PropTypes from 'prop-types'_" but this way does not work;

Do you will update the set of libraries (under client/lib) and the MFAPrompt.js. to help us integrate features into our own React Native app?

Could some one test and post the MFAPrompt.js file with the prop-types correctly setted?

this is a start point: https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#migrating-from-reactproptypes

**Comment by ngoyal16** [comment] 2017-12-06 18:00
the issue is due to the "react-native-prompt". the library is still is in old version of react.

till the prompt library not update you can do manual change in the react-native-prompt package manually in prompt.js file and add "import PropTypes from 'prop-types';" this in that

**Comment by dinhanhhuy** [comment] 2017-12-12 03:32
@ngoyal16 ng
thank you very much :D i remove old import and add the new one... i will york this project to keep it alive when npm install.

**Comment by manueliglesias** [comment] 2018-01-09 18:06
Thank you for trying this starter. The issue has  been addressed in #39

Please feel free to re-open if the issue is still present, or create a new issue if needed

**Closed by manueliglesias** 2018-01-09 18:06 UTC
